version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_LOG_DESTINATION=stderr
      - POSTGRES_LOGGING_COLLECTOR=on
      - POSTGRES_LOG_DIRECTORY=/var/log/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d admin -U admin" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_log:/var/log/postgresql
      - ./db/:/var/lib/postgresql/data
    networks:
      - web_network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - web_network

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
volumes:
  postgres_data:
  postgres_log: